apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: redis-test
  name: redis-test
spec:
  replicas: 1
  selector:
    matchLabels:
      run: redis-test
  template:
    metadata:
      labels:
        run: redis-test
    spec:
      containers:
      - image: redis
        imagePullPolicy: Always
        name: redis-test
        resources:
          limits:
            cpu: 1000m
            memory: 32Mi
          requests:
            cpu: 100m
            memory: 32Mi
