apiVersion: v1
kind: Service
metadata:
  labels:
    run: cloud-native-demo
  name: cloud-native-demo
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: http
  selector:
    run: cloud-native-demo
